name: CI

on:
  pull_request:
    branches:
    - master
  schedule:
  - cron: 0 2 * * 1-5

jobs:
  test:
    name: Test Swift ${{ matrix.swift_version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        swift_version: [4.1]
        os: [ubuntu-latest, ubuntu-16.04, macOS-latest]
    
    steps:
    - uses: actions/checkout@v1
    - name: Install
      run: |
        eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
        swiftenv install ${{ matrix.swift_version }}
        swiftenv local ${{ matrix.swift_version }}
        swift --version
    - name: Test
        swift test --parallel
